version: 2
jobs:
    build:
      docker:
        - image: kalium40/ubuntu-ja-latex:latest
      steps:
        - checkout
        - run: apt-get install pandoc -y
        - run: pandoc --mathjax -s -o index.html README.md
        - store_artifacts:
            path: index.html
            destination: index.html

    deploy:
      docker:
        - image: kalium40/ubuntu-ja-latex:latest
      steps:
        - checkout
        - run: apt-get install pandoc lftp -y
        - run: echo "set ssl:verify-certificate no" >> ~/.lftprc
        - run: pandoc --mathjax -s -o index.html README.md
        - run: lftp -u kalium40.html.xdomain.jp,${FTP_PASSWORD} -e "put index.html;quit" sv2.html.xdomain.ne.jp
        - store_artifacts:
            path: index.html
            destination: index.html

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - deploy:
          filters:
            branches:
              only: master
